author: Mobkinz78
main: com.mobkinz78.swiftswim.Core
name: SwiftSwim
version: 2.0
description: Give players speed when it is raining!
commands: 
  swiftswim:
    description: Allows use of swiftswim
    aliases: [ss]
permissions:
  swiftswim.use:
    default: false
    description: Allowed to use swiftswim.