author: Mobkinz78
main: com.mobkinz78.swiftswim.Core
name: SwiftSwim
version: 1.8
description: "Give players speed when it is raining!"
commands: 
  swiftswim:
    description: Allows use of swiftswim
    aliases: [ss]
  checklist:
    description: prints out the lists
    aliases: []
permissions:
  swiftswim.allowed: 
    default: false
    description: "Allowed to use swiftswim."